# fly.toml app configuration file generated for staylabel on 2025-08-09T19:03:39+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'staylabel'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

# Support multiple domains
[[http_service.http_options.headers]]
  X-Forwarded-Host = "true"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
