create view public.reservations_details as
select
  r.id,
  r.beds24_booking_id,
  r.property_id,
  r.room_type_id,
  r.room_unit_id,
  r.booking_name,
  r.booking_email,
  r.booking_phone,
  r.check_in_date,
  r.check_out_date,
  r.num_guests,
  r.total_amount,
  r.currency,
  r.status,
  r.booking_source,
  r.num_adults,
  r.num_children,
  r.special_requests,
  r.check_in_token,
  r.guest_lastname,
  r.guest_firstname,
  r.guest_contact,
  r.guest_mail,
  r.passport_url,
  r.guest_address,
  r.estimated_checkin_time,
  r.travel_purpose,
  r.emergency_contact_name,
  r.emergency_contact_phone,
  r.agreement_accepted,
  r.checkin_submitted_at,
  r.admin_verified,
  r.verified_at,
  r.verified_by,
  r.created_at,
  r.updated_at,
  r."apiReference",
  r.booking_lastname,
  r."rateDescription",
  r.commission,
  r."apiMessage",
  r."bookingTime",
  r.comments,
  r.price,
  r."timeStamp",
  r.lang,
  r.access_read,
  p.name as property_name,
  p.address as property_address,
  p.owner_id as property_owner_id,
  p.description as property_description,
  p.property_type,
  p.wifi_name as property_wifi_name,
  p.wifi_password as property_wifi_password,
  p.house_rules,
  p.check_in_instructions,
  p.emergency_contact as property_emergency_contact,
  p.property_amenities,
  p.location_info,
  p.is_active as property_is_active,
  p.created_at as property_created_at,
  p.updated_at as property_updated_at,
  p.access_time,
  p.default_cleaner_id,
  p.beds24_property_id,
  rt.name as room_type_name,
  rt.description as room_type_description,
  rt.max_guests as room_type_max_guests,
  rt.base_price,
  rt.currency as room_type_currency,
  rt.room_amenities as room_type_amenities,
  rt.bed_configuration,
  rt.room_size_sqm,
  rt.has_balcony as room_type_has_balcony,
  rt.has_kitchen as room_type_has_kitchen,
  rt.is_accessible as room_type_is_accessible,
  rt.is_active as room_type_is_active,
  rt.created_at as room_type_created_at,
  rt.updated_at as room_type_updated_at,
  rt.beds24_roomtype_id,
  ru.unit_number,
  ru.floor_number,
  ru.access_code,
  ru.access_instructions,
  ru.wifi_name as unit_wifi_name,
  ru.wifi_password as unit_wifi_password,
  ru.unit_amenities,
  ru.maintenance_notes,
  ru.is_active as unit_is_active,
  ru.created_at as unit_created_at,
  ru.updated_at as unit_updated_at,
  ru.beds24_unit_id,
  up.first_name as verified_by_name,
  up.last_name as verified_by_lastname
from
  reservations r
  left join properties p on r.property_id = p.id
  left join room_types rt on r.room_type_id = rt.id
  left join room_units ru on r.room_unit_id = ru.id
  left join user_profiles up on r.verified_by = up.id;